name: bug
description: report a bug in our code
title: "bug@"
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: what happened?
    validations:
      required: true
  - type: textarea
    id: what-did-you-expect
    attributes:
      label: what did you expect to happen?
    validations:
      required: true
